<?php
session_start();
include('script/conexion.php');
require 'resources/Spreadsheet/autoload.php';
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\RichText\RichText;
use PhpOffice\PhpSpreadsheet\Shared\Date;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Color;
use PhpOffice\PhpSpreadsheet\Style\NumberFormat;

$responsable = $_SESSION['id'];
$fecha_inicio = date('Y-m-d');

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue('A1', 'nombre');
$sheet->setCellValue('B1', 'identificacion');
$sheet->setCellValue('C1', 'municipio');
$sheet->setCellValue('D1', 'direccion');
$sheet->setCellValue('E1', 'departamento');
$sheet->setCellValue('F1', 'edad');
$sheet->setCellValue('G1', 'genero');
$sheet->setCellValue('H1', 'estado_civil');
$sheet->setCellValue('I1', 'nivel_escolaridad');
$sheet->setCellValue('J1', 'convive');
$sheet->setCellValue('K1', 'trabaja_actualmente');
$sheet->setCellValue('L1', 'ingreso_mensual');
$sheet->setCellValue('M1', 'radio1_1');
$sheet->setCellValue('N1', 'radio1_2');
$sheet->setCellValue('O1', 'radio1_3');
$sheet->setCellValue('P1', 'radio1_4');
$sheet->setCellValue('Q1', 'radio2_1');
$sheet->setCellValue('R1', 'radio2_2');
$sheet->setCellValue('S1', 'radio2_3');
$sheet->setCellValue('T1', 'radio2_4');
$sheet->setCellValue('U1', 'radio2_5');
$sheet->setCellValue('V1', 'radio2_6');
$sheet->setCellValue('W1', 'radio2_7');
$sheet->setCellValue('X1', 'radio2_8');
$sheet->setCellValue('Y1', 'radio2_9');
$sheet->setCellValue('Z1', 'radio2_10');
$sheet->setCellValue('AA1', 'radio2_11');
$sheet->setCellValue('AB1', 'radio2_12');
$sheet->setCellValue('AC1', 'radio2_13');
$sheet->setCellValue('AD1', 'radio2_14');
$sheet->setCellValue('AE1', 'radio3_1');
$sheet->setCellValue('AF1', 'radio3_2');
$sheet->setCellValue('AG1', 'radio3_3');
$sheet->setCellValue('AH1', 'radio3_4');
$sheet->setCellValue('AI1', 'radio4_1');
$sheet->setCellValue('AJ1', 'radio4_2');
$sheet->setCellValue('AK1', 'radio4_3');
$sheet->setCellValue('AL1', 'radio5_1');
$sheet->setCellValue('AM1', 'radio5_2');
$sheet->setCellValue('AN1', 'radio5_3');
$sheet->setCellValue('AO1', 'radio5_4');
$sheet->setCellValue('AP1', 'radio5_5');
$sheet->setCellValue('AQ1', 'radio6_1');
$sheet->setCellValue('AR1', 'radio6_2');
$sheet->setCellValue('AS1', 'radio6_3');
$sheet->setCellValue('AT1', 'radio6_4');
$sheet->setCellValue('AU1', 'responsable');
$sheet->setCellValue('AV1', 'fecha_creacion');

$fila = 2;

ini_set('memory_limit', '2000M');
$sql1 = "SELECT * FROM encuesta1";
$consulta1 = mysqli_query($conexion,$sql1);
while($row1 = mysqli_fetch_array($consulta1)) {
	$nombre = $row1['nombre'];
	$identificacion = $row1['identificacion'];
	$municipio = $row1['municipio'];
	$direccion = $row1['direccion'];
	$departamento = $row1['departamento'];
	$edad = $row1['edad'];
	$genero = $row1['genero'];
	$estado_civil = $row1['estado_civil'];
	$nivel_escolaridad = $row1['nivel_escolaridad'];
	$convive = $row1['convive'];
	$trabaja_actualmente = $row1['trabaja_actualmente'];
	$ingreso_mensual = $row1['ingreso_mensual'];
	$radio1_1 = $row1['radio1_1'];
	$radio1_2 = $row1['radio1_2'];
	$radio1_3 = $row1['radio1_3'];
	$radio1_4 = $row1['radio1_4'];
	$radio2_1 = $row1['radio2_1'];
	$radio2_2 = $row1['radio2_2'];
	$radio2_3 = $row1['radio2_3'];
	$radio2_4 = $row1['radio2_4'];
	$radio2_5 = $row1['radio2_5'];
	$radio2_6 = $row1['radio2_6'];
	$radio2_7 = $row1['radio2_7'];
	$radio2_8 = $row1['radio2_8'];
	$radio2_9 = $row1['radio2_9'];
	$radio2_10 = $row1['radio2_10'];
	$radio2_11 = $row1['radio2_11'];
	$radio2_12 = $row1['radio2_12'];
	$radio2_13 = $row1['radio2_13'];
	$radio2_14 = $row1['radio2_14'];
	$radio3_1 = $row1['radio3_1'];
	$radio3_2 = $row1['radio3_2'];
	$radio3_3 = $row1['radio3_3'];
	$radio3_4 = $row1['radio3_4'];
	$radio4_1 = $row1['radio4_1'];
	$radio4_2 = $row1['radio4_2'];
	$radio4_3 = $row1['radio4_3'];
	$radio5_1 = $row1['radio5_1'];
	$radio5_2 = $row1['radio5_2'];
	$radio5_3 = $row1['radio5_3'];
	$radio5_4 = $row1['radio5_4'];
	$radio5_5 = $row1['radio5_5'];
	$radio6_1 = $row1['radio6_1'];
	$radio6_2 = $row1['radio6_2'];
	$radio6_3 = $row1['radio6_3'];
	$radio6_4 = $row1['radio6_4'];
	$responsable = $row1['responsable'];
	$fecha_creacion = $row1['fecha_creacion'];

	$spreadsheet->getActiveSheet()->getColumnDimension('A')->setWidth(25);
	$spreadsheet->getActiveSheet()->getColumnDimension('B')->setWidth(25);
	$spreadsheet->getActiveSheet()->getColumnDimension('C')->setWidth(25);
	$spreadsheet->getActiveSheet()->getColumnDimension('D')->setWidth(25);
	$spreadsheet->getActiveSheet()->getColumnDimension('E')->setWidth(25);

	$sheet->setCellValue('A'.$fila, $nombre);
	$sheet->setCellValue('B'.$fila, $identificacion);
	$sheet->setCellValue('C'.$fila, $municipio);
	$sheet->setCellValue('D'.$fila, $direccion);
	$sheet->setCellValue('E'.$fila, $departamento);
	$sheet->setCellValue('F'.$fila, $edad);
	$sheet->setCellValue('G'.$fila, $genero);
	$sheet->setCellValue('H'.$fila, $estado_civil);
	$sheet->setCellValue('I'.$fila, $nivel_escolaridad);
	$sheet->setCellValue('J'.$fila, $convive);
	$sheet->setCellValue('K'.$fila, $trabaja_actualmente);
	$sheet->setCellValue('L'.$fila, $ingreso_mensual);
	$sheet->setCellValue('M'.$fila, $radio1_1);
	$sheet->setCellValue('N'.$fila, $radio1_2);
	$sheet->setCellValue('O'.$fila, $radio1_3);
	$sheet->setCellValue('P'.$fila, $radio1_4);
	$sheet->setCellValue('Q'.$fila, $radio2_1);
	$sheet->setCellValue('R'.$fila, $radio2_2);
	$sheet->setCellValue('S'.$fila, $radio2_3);
	$sheet->setCellValue('T'.$fila, $radio2_4);
	$sheet->setCellValue('U'.$fila, $radio2_5);
	$sheet->setCellValue('V'.$fila, $radio2_6);
	$sheet->setCellValue('W'.$fila, $radio2_7);
	$sheet->setCellValue('X'.$fila, $radio2_8);
	$sheet->setCellValue('Y'.$fila, $radio2_9);
	$sheet->setCellValue('Z'.$fila, $radio2_10);
	$sheet->setCellValue('AA'.$fila, $radio2_11);
	$sheet->setCellValue('AB'.$fila, $radio2_12);
	$sheet->setCellValue('AC'.$fila, $radio2_13);
	$sheet->setCellValue('AD'.$fila, $radio2_14);
	$sheet->setCellValue('AE'.$fila, $radio3_1);
	$sheet->setCellValue('AF'.$fila, $radio3_2);
	$sheet->setCellValue('AG'.$fila, $radio3_3);
	$sheet->setCellValue('AH'.$fila, $radio3_4);
	$sheet->setCellValue('AI'.$fila, $radio4_1);
	$sheet->setCellValue('AJ'.$fila, $radio4_2);
	$sheet->setCellValue('AK'.$fila, $radio4_3);
	$sheet->setCellValue('AL'.$fila, $radio5_1);
	$sheet->setCellValue('AM'.$fila, $radio5_2);
	$sheet->setCellValue('AN'.$fila, $radio5_3);
	$sheet->setCellValue('AO'.$fila, $radio5_4);
	$sheet->setCellValue('AP'.$fila, $radio5_5);
	$sheet->setCellValue('AQ'.$fila, $radio6_1);
	$sheet->setCellValue('AR'.$fila, $radio6_2);
	$sheet->setCellValue('AS'.$fila, $radio6_3);
	$sheet->setCellValue('AT'.$fila, $radio6_4);
	$sheet->setCellValue('AU'.$fila, $responsable);
	$sheet->setCellValue('AV'.$fila, $fecha_creacion);
	$fila = $fila+1;
}

$fecha_inicio1 = date('Y-m-d');
$writer = new Xlsx($spreadsheet);
$writer->save('exportable_encuesta1 '.$fecha_inicio1.'.xlsx');
header("Location: exportable_encuesta1 ".$fecha_inicio1.".xlsx");

?>